# Conclusion
In our pursuit of an ideal career path and a suitable location to seek employment, we first looked at NYC and compared its employment climate with the rest of the country. We then expanded our scope to include the state of NY and its different regions, comparing average salaries across a set of tech jobs that we are interested in. This was supplemented with an analysis of data science, statistics, and software engineering employment figures across a period of 4 years in those regions. On the one hand, these figures helped us form an idea about which specific occupations we may want to pursue (based on compensation figures); on the other hand, they gave us an insight into which regions in the state of NY have a growing tech market and an increasing number of data scientist openings year-over-year. The scope of this analysis was further expanded to include another tech hub in the US, which is California. We looked at San Francisco as another tempting destination. We compared average yearly salaries figures for a set of tech jobs (e.g. Data Scientist, Statistician, Researcher...) in SF, NY and including national averages as a point of reference. What we noticed is that in general, salaries in SF tend to be higher than in NY for the same occupations; However, this doesn't necessarily mean that SF is a better option to seek employment. To get a holistic perspective, which could be considered as a potential extension/future step to this project, we can look at other factors such as cost of living, happiness indexes...

The main challenges we faced in this project relate to data sources. Acquiring, preprocessing and compiling the datasets took the lion's share of the overall time spent on the project. There were also some inconsistencies across the datasets. For example, we found out that "Occupational Employment and Wage Statistics" datasets have slight variations from year to year. Specifically, some columns are missing in a few datasets and some categories' names vary from dataset to dataset. Therefore, we had to manually match a few of them to ensure consistency across the board.

Apart from gaining valuable insights into the tech job market, one valuable lesson we learned is how important data is in making rational decisions. That is, with proper data exploratory techniques, we can eliminate many options that may cloud our judgement and form educated opinions.
