# Introduction

We decided to look into employment and labor statistics in New York City as our topic for this project. The reason we chose this topic was, now that we live here, we are likely looking for internships and potentially jobs in the city and we thought it would be interesting to learn more about the employment landscape in New York City and compare that to the rest of the country. That being said, the question we are focused on answering is how do New York City labor statistics differ from the rest of the country? Does that make a compelling arguement to stay and work here? Or should we seek employment elsewhere?

These labor statistics that we plan to observe include the unemployment rate, number of employed, the labor force, average hourly earnings, average weekly hours, and average weekly earnings. In order to compare to the rest of the country we will need national averages for all these values as well as to compare with other future working areas some cities we would consider moving to for comparison as well. A long with this, when viewing the average hourly earnings it would be interesting to see how that changes over time compared to inflation, to see where our wages would grow accordingly with inflation.

For those that don't know, labor statistics are commonly created each month nationally, state-wide, and by large city governments. They provide information on changes in the current labor market, i.e. the people in that population who are currently working or looking for a job. With this we commonly find the size of the labor force, the amount of the labor force that is employed, the amount of the labor force that is unemployed, and the unemployment rate. When it comes to those listed as unemployed those are people who have worked in the last year and are currently looking for employment. This means we can gain insight if people are being laid off from their jobs if the labor force remains about the same but the unemployment rate rises. Another great resource the New York State Department of Labor provides is the "State and Area Employment, Hours, and Earnings" which provides us the average hourly earnings, average weekly hours worked, and average weekly earnings which we can use to compare how those in the New York city labor force on average are compensated for their work to the national averages and other cities.
